In [1]:
import pandas as pd
from datetime import datetime, timedelta

In [2]:
df = pd.read_csv('churn.csv',parse_dates=['last_trip_date','signup_date'])

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
avg_dist                  50000 non-null float64
avg_rating_by_driver      49799 non-null float64
avg_rating_of_driver      41878 non-null float64
avg_surge                 50000 non-null float64
city                      50000 non-null object
last_trip_date            50000 non-null datetime64[ns]
phone                     49604 non-null object
signup_date               50000 non-null datetime64[ns]
surge_pct                 50000 non-null float64
trips_in_first_30_days    50000 non-null int64
luxury_car_user           50000 non-null bool
weekday_pct               50000 non-null float64
dtypes: bool(1), datetime64[ns](2), float64(6), int64(1), object(2)
memory usage: 4.2+ MB

In [15]:
df.head()

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,city,last_trip_date,phone,signup_date,surge_pct,trips_in_first_30_days,...,weekday_pct,Android,iPhone,others,Astapor,King's Landing,Winterfell,False,True,churn
0,3.67,5.0,4.7,1.10,King's Landing,2014-06-17,iPhone,2014-01-25,15.4,4,...,46.2,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,False
1,8.26,5.0,5.0,1.00,Astapor,2014-05-05,Android,2014-01-29,0.0,0,...,50.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,True
2,0.77,5.0,4.3,1.00,Astapor,2014-01-07,iPhone,2014-01-06,0.0,3,...,100.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,True
3,2.36,4.9,4.6,1.14,King's Landing,2014-06-29,iPhone,2014-01-10,20.0,9,...,80.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,False
4,3.13,4.9,4.4,1.19,Winterfell,2014-03-15,Android,2014-01-27,11.8,14,...,82.4,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,True

In [5]:
type(df['signup_date'][0])

pandas.tslib.Timestamp

In [6]:
df.cov()

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,surge_pct,trips_in_first_30_days,luxury_car_user,weekday_pct
avg_dist,32.573921,0.203818,0.109752,-0.103409,-11.893989,-2.950994,0.089374,21.513372
avg_rating_by_driver,0.203818,0.199498,0.030666,0.001045,0.178330,-0.066365,0.002023,0.337995
avg_rating_of_driver,0.109752,0.030666,0.381107,-0.003247,-0.044296,-0.028295,-0.000626,0.314834
avg_surge,-0.103409,0.001045,-0.003247,0.049433,3.521571,-0.001552,-0.008490,-0.907486
surge_pct,-11.893989,0.178330,-0.044296,3.521571,398.354132,0.432980,-1.033692,-107.254522
trips_in_first_30_days,-2.950994,-0.066365,-0.028295,-0.001552,0.432980,14.384452,0.206260,7.086451
luxury_car_user,0.089374,0.002023,-0.000626,-0.008490,-1.033692,0.206260,0.234895,0.646953
weekday_pct,21.513372,0.337995,0.314834,-0.907486,-107.254522,7.086451,0.646953,1375.037895

In [7]:
df.corr()

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,surge_pct,trips_in_first_30_days,luxury_car_user,weekday_pct
avg_dist,1.000000,0.080540,0.034509,-0.081491,-0.104414,-0.136329,0.032310,0.101652
avg_rating_by_driver,0.080540,1.000000,0.123175,0.010597,0.020103,-0.039115,0.009343,0.020442
avg_rating_of_driver,0.034509,0.123175,1.000000,-0.026189,-0.003899,-0.011302,-0.002086,0.014630
avg_surge,-0.081491,0.010597,-0.026189,1.000000,0.793582,-0.001841,-0.078791,-0.110071
surge_pct,-0.104414,0.020103,-0.003899,0.793582,1.000000,0.005720,-0.106861,-0.144918
trips_in_first_30_days,-0.136329,-0.039115,-0.011302,-0.001841,0.005720,1.000000,0.112210,0.050388
luxury_car_user,0.032310,0.009343,-0.002086,-0.078791,-0.106861,0.112210,1.000000,0.035998
weekday_pct,0.101652,0.020442,0.014630,-0.110071,-0.144918,0.050388,0.035998,1.000000

In [8]:
df['city'].unique()

array(["King's Landing", 'Astapor', 'Winterfell'], dtype=object)

In [16]:
df['avg_rating_by_driver'] = df['avg_rating_by_driver'].fillna(df['avg_rating_by_driver'].sum()*1.0/len(df['avg_rating_by_driver']))

In [17]:
df['avg_rating_of_driver'] = df['avg_rating_of_driver'].fillna(df['avg_rating_of_driver'].sum()*1.0/len(df['avg_rating_of_driver']))

In [11]:
df['phone'] = df['phone'].fillna('others')

In [12]:
df = pd.concat((df, pd.get_dummies(df['phone']), pd.get_dummies(df['city']),pd.get_dummies(df['luxury_car_user'])), axis=1)

In [18]:
df.head()

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,city,last_trip_date,phone,signup_date,surge_pct,trips_in_first_30_days,...,weekday_pct,Android,iPhone,others,Astapor,King's Landing,Winterfell,False,True,churn
0,3.67,5.0,4.7,1.10,King's Landing,2014-06-17,iPhone,2014-01-25,15.4,4,...,46.2,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,False
1,8.26,5.0,5.0,1.00,Astapor,2014-05-05,Android,2014-01-29,0.0,0,...,50.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,True
2,0.77,5.0,4.3,1.00,Astapor,2014-01-07,iPhone,2014-01-06,0.0,3,...,100.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,True
3,2.36,4.9,4.6,1.14,King's Landing,2014-06-29,iPhone,2014-01-10,20.0,9,...,80.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,False
4,3.13,4.9,4.4,1.19,Winterfell,2014-03-15,Android,2014-01-27,11.8,14,...,82.4,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,True

In [34]:
df['churn'] = datetime(2014, 7, 1) - df['last_trip_date'] <= timedelta(days=30)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 21 columns):
avg_dist                  50000 non-null float64
avg_rating_by_driver      50000 non-null float64
avg_rating_of_driver      50000 non-null float64
avg_surge                 50000 non-null float64
city                      50000 non-null object
last_trip_date            50000 non-null datetime64[ns]
phone                     50000 non-null object
signup_date               50000 non-null datetime64[ns]
surge_pct                 50000 non-null float64
trips_in_first_30_days    50000 non-null int64
luxury_car_user           50000 non-null bool
weekday_pct               50000 non-null float64
Android                   50000 non-null float64
iPhone                    50000 non-null float64
others                    50000 non-null float64
Astapor                   50000 non-null float64
King's Landing            50000 non-null float64
Winterfell                50000 non-null float64
False                     50000 non-null float64
True                      50000 non-null float64
churn                     50000 non-null bool
dtypes: bool(2), datetime64[ns](2), float64(14), int64(1), object(2)
memory usage: 7.3+ MB

In [23]:
df.rename(columns={'True': 'Luxury_car_user', 'False': 'Non_luxury_car_user'}, inplace=True)

In [25]:
df.head()

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,city,last_trip_date,phone,signup_date,surge_pct,trips_in_first_30_days,...,weekday_pct,Android,iPhone,others,Astapor,King's Landing,Winterfell,False,True,churn
0,3.67,5.0,4.7,1.10,King's Landing,2014-06-17,iPhone,2014-01-25,15.4,4,...,46.2,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,False
1,8.26,5.0,5.0,1.00,Astapor,2014-05-05,Android,2014-01-29,0.0,0,...,50.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,True
2,0.77,5.0,4.3,1.00,Astapor,2014-01-07,iPhone,2014-01-06,0.0,3,...,100.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,True
3,2.36,4.9,4.6,1.14,King's Landing,2014-06-29,iPhone,2014-01-10,20.0,9,...,80.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,False
4,3.13,4.9,4.4,1.19,Winterfell,2014-03-15,Android,2014-01-27,11.8,14,...,82.4,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,True

In [30]:
from statsmodels.graphics.correlation import plot_corr
import matplotlib.pyplot as plt

In [35]:
sum(df['churn'] == 0)

31196

In [41]:
df.corr()

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,surge_pct,trips_in_first_30_days,luxury_car_user,weekday_pct,Android,iPhone,others,Astapor,King's Landing,Winterfell,False,True,churn
avg_dist,1.000000,0.079781,-0.032230,-0.081491,-0.104414,-0.136329,0.032310,0.101652,0.020888,-0.025030,0.022372,-0.045431,0.015877,0.030050,-0.032310,0.032310,-0.092780
avg_rating_by_driver,0.079781,1.000000,0.088048,0.010427,0.019904,-0.039018,0.009403,0.020402,0.008762,-0.010122,0.007419,0.032534,0.084481,-0.098743,-0.009403,0.009403,-0.026678
avg_rating_of_driver,-0.032230,0.088048,1.000000,-0.022453,-0.000040,0.075864,0.014354,0.021078,-0.001475,0.002832,-0.007122,0.016623,0.095281,-0.092439,-0.014354,0.014354,0.060103
avg_surge,-0.081491,0.010427,-0.022453,1.000000,0.793582,-0.001841,-0.078791,-0.110071,-0.008977,0.011104,-0.011423,0.037172,-0.009198,-0.027643,0.078791,-0.078791,-0.003333
surge_pct,-0.104414,0.019904,-0.000040,0.793582,1.000000,0.005720,-0.106861,-0.144918,-0.010150,0.012851,-0.014456,0.045457,0.028221,-0.065603,0.106861,-0.106861,0.011797
trips_in_first_30_days,-0.136329,-0.039018,0.075864,-0.001841,0.005720,1.000000,0.112210,0.050388,-0.059309,0.058342,0.002786,-0.061075,0.024650,0.037735,-0.112210,0.112210,0.210463
luxury_car_user,0.032310,0.009403,0.014354,-0.078791,-0.106861,0.112210,1.000000,0.035998,-0.075836,0.067002,0.043145,0.021259,0.039649,-0.051990,-1.000000,1.000000,0.205002
weekday_pct,0.101652,0.020402,0.021078,-0.110071,-0.144918,0.050388,0.035998,1.000000,-0.009241,0.006726,0.012753,-0.010540,0.031349,-0.015318,-0.035998,0.035998,0.009693
Android,0.020888,0.008762,-0.001475,-0.008977,-0.010150,-0.059309,-0.075836,-0.009241,1.000000,-0.981471,-0.058554,0.025642,-0.059203,0.023517,0.075836,-0.075836,-0.225464
iPhone,-0.025030,-0.010122,0.002832,0.011104,0.012851,0.058342,0.067002,0.006726,-0.981471,1.000000,-0.133814,-0.024539,0.060520,-0.025618,-0.067002,0.067002,0.225244
others,0.022372,0.007419,-0.007122,-0.011423,-0.014456,0.002786,0.043145,0.012753,-0.058554,-0.133814,1.000000,-0.004772,-0.009111,0.011840,-0.043145,0.043145,-0.007419
Astapor,-0.045431,0.032534,0.016623,0.037172,0.045457,-0.061075,0.021259,-0.010540,0.025642,-0.024539,-0.004772,1.000000,-0.354298,-0.657563,-0.021259,0.021259,-0.174655
King's Landing,0.015877,0.084481,0.095281,-0.009198,0.028221,0.024650,0.039649,0.031349,-0.059203,0.060520,-0.009111,-0.354298,1.000000,-0.471555,-0.039649,0.039649,0.262284
Winterfell,0.030050,-0.098743,-0.092439,-0.027643,-0.065603,0.037735,-0.051990,-0.015318,0.023517,-0.025618,0.011840,-0.657563,-0.471555,1.000000,0.051990,-0.051990,-0.046611
False,-0.032310,-0.009403,-0.014354,0.078791,0.106861,-0.112210,-1.000000,-0.035998,0.075836,-0.067002,-0.043145,-0.021259,-0.039649,0.051990,1.000000,-1.000000,-0.205002
True,0.032310,0.009403,0.014354,-0.078791,-0.106861,0.112210,1.000000,0.035998,-0.075836,0.067002,0.043145,0.021259,0.039649,-0.051990,-1.000000,1.000000,0.205002
churn,-0.092780,-0.026678,0.060103,-0.003333,0.011797,0.210463,0.205002,0.009693,-0.225464,0.225244,-0.007419,-0.174655,0.262284,-0.046611,-0.205002,0.205002,1.000000

In [ ]:

pd.scatter_matrix(df, alpha=0.2, figsize=(15,15), diagonal='kde')
plt.show()

In [ ]:
plt.matshow(df.corr())
plt.show()